export type ContactItem = {
    readonly iconClassName: string;
    readonly label?: string;
    readonly text: string;
    readonly href?: string;
};

export type Project = {
    readonly name: string;
    readonly url: string;
};

export type WorkExperience = {
    readonly company: string;
    readonly url?: string;
    readonly period: string;
    readonly roles: readonly WorkRole[];
};

export type WorkRole = {
    readonly title: string;
    readonly description: readonly string[];
    readonly links?: readonly string[];
};

export const aboutText =
    "I am a full-stack developer with over 10 years of experience in software development, specializing in web applications. I focus on building practical, maintainable products and enjoy working with teams that want to create lasting value for Hong Kong's IT industry.";

export const contactItems: readonly ContactItem[] = [
    {
        iconClassName: "fas fa-phone fa-fw",
        text: "51136101",
    },
    {
        iconClassName: "fas fa-envelope fa-fw",
        text: "hososlch@gmail.com",
        href: "mailto:hososlch@gmail.com",
    },
    {
        iconClassName: "fab fa-linkedin fa-fw",
        label: "LinkedIn",
        text: "anthony-lee-77851376",
        href: "https://www.linkedin.com/in/anthony-lee-77851376/",
    },
];

export const projects: readonly Project[] = [
    {
        name: "Hung Fook Tong BB Card",
        url: "http://www.hungfooktong.com/bbcard/orderform.php",
    },
    {
        name: "全治護脊",
        url: "http://www.hkwholeness.com/",
    },
    {
        name: "Tai Shing Securities Website",
        url: "https://www.taishinghk.com",
    },
    {
        name: "Soka Kindergarten",
        url: "https://www.soka.edu.hk/",
    },
    {
        name: "香港掂檔 十大匠人選舉 2020",
        url: "https://game.madeinhk.com.hk/",
    },
    {
        name: "鴻福堂 - 自家 Club 會員尊享",
        url: "https://www.hungfooktong.com/member/jika_registration_form/",
    },
    {
        name: "鴻福堂 – 自家喜慶系列",
        url: "https://www.hungfooktong.com/joyousseries/",
    },
    {
        name: "鴻福堂【有機滴雞精】",
        url: "https://www.hungfooktong.com/chickenessence/",
    },
    {
        name: "鴻福堂【滴虱目魚精】",
        url: "https://www.hungfooktong.com/fishessence/",
    },
    {
        name: "鴻福堂【黃金蜆精】",
        url: "https://www.hungfooktong.com/clamessence/",
    },
    {
        name: "鴻福堂 - 夏日穿越宮略",
        url: "https://www.hungfooktong.com/summer-palace/",
    },
];

export const skills: readonly string[] = [
    "ASP.NET",
    "CSS",
    "Database Design",
    "Docker",
    "E-commerce",
    "HTML5",
    "Java",
    "JavaScript",
    "MySQL",
    "PostgreSQL",
    "Node.js",
    "PHP",
    "Python",
    "React.js",
    "Redux",
    "redux-saga",
    "Zustand",
    "Ruby on Rails",
    "Web Design",
    "Web Development",
];

export const workExperiences: readonly WorkExperience[] = [
    {
        company: "Pinnacle Enterprise Holdings Ltd",
        url: "https://www.linkedin.com/company/pinnacle-enterprise-holdings-ltd/",
        period: "February 2021 –",
        roles: [
            {
                title: "Front-end Developer",
                description: [
                    "Building and developing a lottery platform and back-office system.",
                    "Front-end: React, TypeScript, redux, redux-saga.",
                    "Back-end: core-fe (Spring like back-end framework)",
                ],
            },
        ],
    },
    {
        company: "SHERGON Print",
        url: "https://www.linkedin.com/company/shergon-print/",
        period: "February 2019 – Apr 2021",
        roles: [
            {
                title: "Full-stack Developer",
                description: ["Back-end: Ruby on Rails", "Front-end: React."],
                links: ["https://qurtty.io/"],
            },
        ],
    },
    {
        company: "Proactive System",
        period: "January 2017 – February 2019",
        roles: [
            {
                title: "Software Engineer",
                description: [
                    "Developing a middle size insurance broker system for a well-known broker.",
                    "Develop a chatbot system for people to integrate their Facebook page with chatbot easily.",
                    "1 year secondment in PCCW.",
                ],
            },
        ],
    },
    {
        company: "Success Finance Limited",
        url: "https://www.linkedin.com/company/success-finance-limited/",
        period: "July 2016 – January 2017",
        roles: [
            {
                title: "Programmer",
                description: [
                    "Developing an analytic system with data visualization that helps the sales manager to know the sales performance and revenue are generated by each sales agent and its subordinates.",
                ],
            },
        ],
    },
    {
        company: "Bonjour Holdings Limited",
        period: "April 2014 – June 2014",
        roles: [
            {
                title: "Part-time Programmer",
                description: ["Helping to fix the front-end of the membership card system."],
            },
        ],
    },
    {
        company: "ECBuy Trading Limited",
        period: "July 2013 – September 2013",
        roles: [
            {
                title: "Part-time Programmer",
                description: ["Developing an E-Commerce system with OpenCart and helping with payment gateway integration."],
            },
        ],
    },
];
