export interface ContactItem {
    iconClassName: string;
    label?: string;
    text: string;
    href?: string;
}

export interface Project {
    name: string;
    url: string;
}

export interface WorkExperience {
    company: string;
    url?: string;
    period: string;
    roles: WorkRole[];
}

export interface WorkRole {
    title: string;
    description: string[];
    links?: string[];
}

export const aboutText =
    "I am a full-stack developer with over 10 years of experience in software development, specializing in web applications. I focus on building practical, maintainable products and enjoy working with teams that want to create lasting value for Hong Kong's IT industry.";

export const contactItems: readonly ContactItem[] = [
    {
        iconClassName: "fas fa-phone fa-fw",
        text: "51136101",
    },
    {
        iconClassName: "fas fa-envelope fa-fw",
        text: "hososlch@gmail.com",
        href: "mailto:hososlch@gmail.com",
    },
    {
        iconClassName: "fab fa-linkedin fa-fw",
        label: "LinkedIn",
        text: "anthony-lee-77851376",
        href: "https://www.linkedin.com/in/anthony-lee-77851376/",
    },
];

export const projects: readonly Project[] = [
    {
        name: "Hung Fook Tong BB Card",
        url: "http://www.hungfooktong.com/bbcard/orderform.php",
    },
    {
        name: "全治護脊",
        url: "http://www.hkwholeness.com/",
    },
    {
        name: "Tai Shing Securities Website",
        url: "https://www.taishinghk.com",
    },
    {
        name: "Soka Kindergarten",
        url: "https://www.soka.edu.hk/",
    },
    {
        name: "香港掂檔 十大匠人選舉 2020",
        url: "https://game.madeinhk.com.hk/",
    },
    {
        name: "鴻福堂 - 自家 Club 會員尊享",
        url: "https://www.hungfooktong.com/member/jika_registration_form/",
    },
    {
        name: "鴻福堂 – 自家喜慶系列",
        url: "https://www.hungfooktong.com/joyousseries/",
    },
    {
        name: "鴻福堂【有機滴雞精】",
        url: "https://www.hungfooktong.com/chickenessence/",
    },
    {
        name: "鴻福堂【滴虱目魚精】",
        url: "https://www.hungfooktong.com/fishessence/",
    },
    {
        name: "鴻福堂【黃金蜆精】",
        url: "https://www.hungfooktong.com/clamessence/",
    },
    {
        name: "鴻福堂 - 夏日穿越宮略",
        url: "https://www.hungfooktong.com/summer-palace/",
    },
];

export const skills: readonly string[] = [
    "ASP.NET",
    "CSS",
    "Database Design",
    "Docker",
    "E-commerce",
    "HTML5",
    "Java",
    "JavaScript",
    "MySQL",
    "PostgreSQL",
    "Node.js",
    "PHP",
    "Python",
    "React.js",
    "Redux",
    "redux-saga",
    "Zustand",
    "Ruby on Rails",
    "Web Design",
    "Web Development",
];

export const workExperiences: readonly WorkExperience[] = [
    {
        company: "Pinnacle Enterprise Holdings Ltd",
        url: "https://www.linkedin.com/company/pinnacle-enterprise-holdings-ltd/",
        period: "February 2021 –",
        roles: [
            {
                title: "Front-end Developer",
                description: [
                    "Develop and maintain a lottery platform and back-office system.",
                    "Build front-end features with React, TypeScript, Redux, and redux-saga.",
                    "Integrate with core-fe, a Spring-like back-end framework.",
                ],
            },
        ],
    },
    {
        company: "SHERGON Print",
        url: "https://www.linkedin.com/company/shergon-print/",
        period: "February 2019 – Apr 2021",
        roles: [
            {
                title: "Full-stack Developer",
                description: ["Built back-end services with Ruby on Rails.", "Developed front-end features with React."],
                links: ["https://qurtty.io/"],
            },
        ],
    },
    {
        company: "Proactive System",
        period: "January 2017 – February 2019",
        roles: [
            {
                title: "Software Engineer",
                description: [
                    "Developed a mid-sized insurance broker system for a well-known brokerage.",
                    "Built a chatbot platform that lets businesses connect Facebook pages to chatbots easily.",
                    "Completed a one-year secondment at PCCW.",
                ],
            },
        ],
    },
    {
        company: "Success Finance Limited",
        url: "https://www.linkedin.com/company/success-finance-limited/",
        period: "July 2016 – January 2017",
        roles: [
            {
                title: "Programmer",
                description: ["Developed an analytics and data visualization system that helped sales managers track performance and revenue generated by each sales agent and their subordinates."],
            },
        ],
    },
    {
        company: "Bonjour Holdings Limited",
        period: "April 2014 – June 2014",
        roles: [
            {
                title: "Part-time Programmer",
                description: ["Fixed front-end issues in the membership card system."],
            },
        ],
    },
    {
        company: "ECBuy Trading Limited",
        period: "July 2013 – September 2013",
        roles: [
            {
                title: "Part-time Programmer",
                description: ["Developed an e-commerce system with OpenCart and integrated payment gateway features."],
            },
        ],
    },
];
